module.exports = {
  component: 'fa',
  icons: {
    regular: ['faCalendarAlt', 'faEdit'],
    solid: [
      'faSearch',
      'faCode',
      'faCaretRight',
      'faMapMarkerAlt',
      'faEnvelope',
      'faShareSquare',
      'faChevronCircleRight',
      'faExternalLinkAlt',
      'faCubes',
      'faTools',
      'faDesktop',
      'faPodcast',
      'faCheckCircle',
    ],
    brands: [
      'faHtml5',
      'faJs',
      'faCss3Alt',
      'faGithub',
      'faGithubSquare',
      'faInstagram',
      'faTwitter',
      'faTwitterSquare',
      'faMedium',
      'faMediumM',
      'faDev',
      'faCodepen',
      'faFacebook',
      'faFacebookSquare',
      'faLinkedin',
      'faLinkedinIn',
      'faReddit',
      'faHackerNews',
    ],
  },
};
